on:
  push:
    branches:
      - ci-test

name: targets

jobs:
  targets:
    runs-on: macOS-latest
    env:
      BRANCH_RUNS: targets-runs # Branch to upload current and historical runs.
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Identify R packages
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-custom_suffix-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-custom_suffix-

      - name: Install R packages
        run: remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Cache targets data store
        id: cache-targets
        uses: actions/cache@v2
        with:
          # List _targets/ and any custom output files below.
          # Delete index.html if the pipeline does not render this report.
          path: |
            _targets/
            index.html
          key: ${{ runner.os }}-targets-${{ hashFiles('_targets/meta/meta') }}
          restore-keys: ${{ runner.os }}-targets-

      - name: Run targets pipeline
        run: targets::tar_make()
        shell: Rscript {0}

      - name: Upload latest run
        run: |
          echo step1
          git fetch $BRANCH_RUNS || git checkout --orphan $BRANCH_RUNS
          echo step2
          git checkout ci-test
          echo step3
          echo ${{ steps.cache-targets.inputs.path }}
          echo step4
          git add -f _targets index.html
          echo step5
          git commit -am "Upload latest run"
          echo step6
          echo checkout
          echo step7
          git checkout $BRANCH_RUNS
          echo step8
          git cherry-pick ci-test || true
          echo step9
          git push -u origin $BRANCH_RUNS
